name: 'Kind Cluster Validation'
description: 'Validate Kind cluster configuration files'
author: 'crac-ci'

branding:
  icon: 'server'
  color: 'purple'

inputs:
  config-path:
    description: 'Path to Kind cluster config file'
    required: true
  kind-version:
    description: 'Kind version to use for validation'
    required: false
    default: '0.22.0'
  kubernetes-version:
    description: 'Expected Kubernetes version'
    required: false
    default: ''
  validate-schema:
    description: 'Validate against Kind config schema'
    required: false
    default: 'true'
  check-node-config:
    description: 'Validate node configuration'
    required: false
    default: 'true'

outputs:
  valid:
    description: 'Whether the config is valid'
    value: ${{ steps.validate.outputs.valid }}
  node-count:
    description: 'Number of nodes in configuration'
    value: ${{ steps.validate.outputs.node_count }}
  error-message:
    description: 'Error message if validation failed'
    value: ${{ steps.validate.outputs.error_message }}

runs:
  using: 'composite'
  steps:
    - name: Setup Kind
      shell: bash
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v${{ inputs.kind-version }}/kind-linux-amd64
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind

    - name: Install yq
      shell: bash
      run: |
        sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
        sudo chmod +x /usr/local/bin/yq

    - name: Validate Kind Configuration
      id: validate
      shell: bash
      run: |
        CONFIG_FILE="${{ inputs.config-path }}"
        VALID="true"
        ERROR_MSG=""
        NODE_COUNT=0

        echo "Validating Kind configuration: ${CONFIG_FILE}"
        echo "=============================================="

        # Check file exists
        if [[ ! -f "${CONFIG_FILE}" ]]; then
          echo "::error::Config file not found: ${CONFIG_FILE}"
          echo "valid=false" >> $GITHUB_OUTPUT
          echo "error_message=Config file not found" >> $GITHUB_OUTPUT
          exit 1
        fi

        # Validate YAML syntax
        echo "Checking YAML syntax..."
        if ! yq eval '.' "${CONFIG_FILE}" > /dev/null 2>&1; then
          echo "::error::Invalid YAML syntax"
          VALID="false"
          ERROR_MSG="Invalid YAML syntax"
        fi

        # Check Kind config structure
        echo "Checking Kind config structure..."
        KIND_TYPE=$(yq eval '.kind // ""' "${CONFIG_FILE}")
        API_VERSION=$(yq eval '.apiVersion // ""' "${CONFIG_FILE}")

        if [[ "${KIND_TYPE}" != "Cluster" ]]; then
          echo "::error::Invalid kind: expected 'Cluster', got '${KIND_TYPE}'"
          VALID="false"
          ERROR_MSG="${ERROR_MSG}; Invalid kind type"
        fi

        if [[ ! "${API_VERSION}" =~ ^kind\.x-k8s\.io/ ]]; then
          echo "::error::Invalid apiVersion: ${API_VERSION}"
          VALID="false"
          ERROR_MSG="${ERROR_MSG}; Invalid apiVersion"
        fi

        # Count and validate nodes
        if [[ "${{ inputs.check-node-config }}" == "true" ]]; then
          echo "Checking node configuration..."

          NODE_COUNT=$(yq eval '.nodes | length' "${CONFIG_FILE}" 2>/dev/null || echo "0")
          echo "Node count: ${NODE_COUNT}"

          if [[ "${NODE_COUNT}" -eq 0 ]]; then
            echo "::warning::No nodes defined - Kind will use default single node"
            NODE_COUNT=1
          fi

          # Check for control-plane node
          CONTROL_PLANE_COUNT=$(yq eval '[.nodes[] | select(.role == "control-plane")] | length' "${CONFIG_FILE}" 2>/dev/null || echo "0")
          if [[ "${CONTROL_PLANE_COUNT}" -eq 0 && "${NODE_COUNT}" -gt 0 ]]; then
            echo "::warning::No control-plane node explicitly defined"
          fi

          # Validate node images if specified
          while IFS= read -r image; do
            if [[ -n "${image}" && "${image}" != "null" ]]; then
              echo "Node image: ${image}"
              if [[ ! "${image}" =~ kindest/node ]]; then
                echo "::warning::Non-standard Kind node image: ${image}"
              fi
            fi
          done < <(yq eval '.nodes[].image // ""' "${CONFIG_FILE}" 2>/dev/null)
        fi

        # Check Kubernetes version if specified
        if [[ -n "${{ inputs.kubernetes-version }}" ]]; then
          echo "Checking Kubernetes version compatibility..."
          EXPECTED_VERSION="${{ inputs.kubernetes-version }}"

          CONFIG_VERSION=$(yq eval '.nodes[0].image // ""' "${CONFIG_FILE}" | grep -oP 'v\d+\.\d+' || echo "")
          if [[ -n "${CONFIG_VERSION}" && "${CONFIG_VERSION}" != "v${EXPECTED_VERSION%.*}" ]]; then
            echo "::warning::Kubernetes version mismatch: expected ${EXPECTED_VERSION}, found ${CONFIG_VERSION}"
          fi
        fi

        # Validate networking configuration
        echo "Checking networking configuration..."
        NETWORKING=$(yq eval '.networking // {}' "${CONFIG_FILE}")
        if [[ "${NETWORKING}" != "{}" ]]; then
          POD_SUBNET=$(yq eval '.networking.podSubnet // ""' "${CONFIG_FILE}")
          SERVICE_SUBNET=$(yq eval '.networking.serviceSubnet // ""' "${CONFIG_FILE}")

          if [[ -n "${POD_SUBNET}" ]]; then
            echo "Pod subnet: ${POD_SUBNET}"
          fi
          if [[ -n "${SERVICE_SUBNET}" ]]; then
            echo "Service subnet: ${SERVICE_SUBNET}"
          fi
        fi

        # Check for extra port mappings
        PORT_MAPPINGS=$(yq eval '[.nodes[].extraPortMappings // [] | .[]] | length' "${CONFIG_FILE}" 2>/dev/null || echo "0")
        if [[ "${PORT_MAPPINGS}" -gt 0 ]]; then
          echo "Extra port mappings: ${PORT_MAPPINGS}"
        fi

        # Check for extra mounts
        EXTRA_MOUNTS=$(yq eval '[.nodes[].extraMounts // [] | .[]] | length' "${CONFIG_FILE}" 2>/dev/null || echo "0")
        if [[ "${EXTRA_MOUNTS}" -gt 0 ]]; then
          echo "Extra mounts: ${EXTRA_MOUNTS}"
        fi

        # Dry run validation with Kind
        if [[ "${{ inputs.validate-schema }}" == "true" ]]; then
          echo ""
          echo "Running Kind dry-run validation..."
          if ! kind create cluster --config "${CONFIG_FILE}" --name test-validation --dry-run 2>&1; then
            echo "::error::Kind config validation failed"
            VALID="false"
            ERROR_MSG="${ERROR_MSG}; Kind dry-run validation failed"
          else
            echo "Kind dry-run validation passed"
          fi
        fi

        echo ""
        echo "=============================================="
        echo "Validation result: ${VALID}"

        echo "valid=${VALID}" >> $GITHUB_OUTPUT
        echo "node_count=${NODE_COUNT}" >> $GITHUB_OUTPUT
        echo "error_message=${ERROR_MSG}" >> $GITHUB_OUTPUT

        if [[ "${VALID}" != "true" ]]; then
          exit 1
        fi
